### ISSUE TITLE
[Change Request] Make sure user dont lockup when entering the wrong password

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6-workshop#135]
**Description**
Set the

```yaml
password_policy:
  # maximum number of failed login attempts before the user is locked out for
  # a certain amount of time. Default is 5.
  max_failed_attempts: 5
```
